{
 "title": "JWT-Pizza-Dashboard",
 "description": "Dashboard displaying the metrics for my JWT Pizza website.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "endpoint_latency_milliseconds_total{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pizza_creation_latency_milliseconds_total{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REVENUE / MINUTE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_revenue_BTC_total{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PIZZA PURCHASES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pizza_sold_count_total{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "failed_pizza_creation_count_total{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL REQUESTS / MINUTE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "http_requests_per_min_count_total{endpoint=\"PUT put\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_requests_per_min_count_total{endpoint=\"GET get\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_requests_per_min_count_total{endpoint=\"POST post\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_requests_per_min_count_total{endpoint=\"DELETE delete\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AUTH ATTEMPTS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "auth_successful_attempts_count_total{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "auth_failed_attempts_count_total{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ALL ACTIVE USERS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "active_users_count_total{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU & MEMORY USAGE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent_total{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_usage_percent_total{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}